apiVersion: v2
name: diabetes-api
description: Helm chart to deploy the Diabetes Prediction FastAPI application using Docker and Kubernetes
type: application

# Chart version (used by Helm itself)
version: 0.1.0

# Application version (your container/app version)
appVersion: "1.0.0"

keywords:
  - fastapi
  - mlops
  - machine-learning
  - api
  - kubernetes
  - python

home: https://github.com/santygo83/my-mlops-project

sources:
  - https://github.com/santygo83/my-mlops-project

maintainers:
  - name: Santosh Kamble
    email: santosh.kamble@example.com

annotations:
  category: mlops
  managed-by: helm

