apiVersion: v1
kind: Service
metadata:
  name: diabetes-api
  labels:
    app: diabetes-api
spec:
  type: ClusterIP
  selector:
    app: diabetes-api
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.container.port }}

